# Generated by Django 5.0.1 on 2024-02-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_schemes_benefits_remove_schemes_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemes',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schemes',
            name='duration',
            field=models.TextField(blank=True),
        ),
    ]
