# Generated by Django 5.0.1 on 2024-02-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_profile_user_alter_schemes_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
