# Generated by Django 5.0.1 on 2024-02-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_profile_phoneno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phoneno',
        ),
    ]
