# Generated by Django 5.0.1 on 2024-02-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phoneno',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profimag',
            field=models.ImageField(default='default.png', upload_to='profimages'),
        ),
    ]
