# Generated by Django 5.0.1 on 2024-02-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_profile_phoneno_alter_profile_profimag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phoneno',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
