# Generated by Django 5.0.1 on 2024-02-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_schemes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemes',
            name='state',
            field=models.CharField(max_length=200),
        ),
    ]
