# Generated by Django 5.0.1 on 2024-02-16 07:10

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_schemes_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemes',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
