# Generated by Django 5.0.1 on 2024-02-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_schemes_desc_schemes_benefits_schemes_doc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemes',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='schemes',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='schemes',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='schemes',
            name='elibilty',
        ),
        migrations.AddField(
            model_name='schemes',
            name='hindi_pdf',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='schemes',
            name='pdf',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
