# Generated by Django 5.0.1 on 2024-02-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_schemes_video_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='curr_user',
            field=models.CharField(max_length=100),
        ),
    ]
