# Generated by Django 5.0.1 on 2024-02-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_chats_curr_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='crophealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('growth_stage', models.TextField()),
                ('condition', models.TextField()),
                ('issues', models.TextField()),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
