# Generated by Django 5.0.1 on 2024-02-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_crophealth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='schemes',
            name='state',
            field=models.TextField(),
        ),
    ]
