# Generated by Django 5.0.1 on 2024-02-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_profile_uid_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneno',
            field=models.IntegerField(null=True),
        ),
    ]
