# Generated by Django 5.0.1 on 2024-02-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_profile_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneno',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
