# Generated by Django 5.0.1 on 2024-02-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_profile_phoneno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
